In [1]:
import numpy as np
from scipy.special import softmax
import gomoku, player_basic

# for auto-reloading external modules
%load_ext autoreload
%autoreload 2

# Playtest

In [15]:
game = gomoku.Gomoku(15)
opponent = player_basic.FeaturePlayer('cp', -1) # human goes first, cp goes second

In [16]:
game.play(7, 7) # human move
if not game.finished:
    game.play(*opponent.play(game)) # cp plays random move
else:
    print("game has ended")
game.show()

   0 1 2 3 4 5 6 7 8 91011121314
 0 . . . . . . . . . . . . . . . 
 1 . . . . . . . . . . . . . . . 
 2 . . . . . . . . . . . . . . . 
 3 . . . . . . . . . . . . . . . 
 4 . . . . . . . . . . . . . . . 
 5 . . . . . . . . . . . . . . . 
 6 . . . . . . . . ○ . . . . . . 
 7 . . . . . . . ● . . . . . . . 
 8 . . . . . . . . . . . . . . . 
 9 . . . . . . . . . . . . . . . 
10 . . . . . . . . . . . . . . . 
11 . . . . . . . . . . . . . . . 
12 . . . . . . . . . . . . . . . 
13 . . . . . . . . . . . . . . . 
14 . . . . . . . . . . . . . . . 


# Testing: PGFeaturePlayer

In [4]:
p1 = player_basic.PGFeaturePlayer('player1', 0, epsilon=0.2, discount=.5)
p2 = player_basic.PGFeaturePlayer('player2', 0, epsilon=0.2, discount=.5)
p2.w = p1.w
#p1.theta = np.array([1, 4, 9, 16, 1, 4, 9, 16, 0], dtype=float)
p2.theta = p1.theta

In [5]:
for i in range(1000):
    if i%10 == 0:
        print(i, end=', ')
    game = gomoku.Gomoku(9)
    p1color = np.random.choice([1, -1])
    p1.piece = p1color
    p2.piece = -p1color

    players = [p1, p2]
    turn = (1-p1color)//2
    while not game.finished:
        game.play(*players[turn].play(game))
        turn = (turn+1)%2
    
    if game.winner == p1color:
        p1_grads = p1.get_grad(game, game._moves_left)
        p2_grads = p2.get_grad(game, 0)
    elif game.winner == -p1color:
        p1_grads = p1.get_grad(game, 0)
        p2_grads = p2.get_grad(game, game._moves_left)
    else:
        p1_grads = p1.get_grad(game, 0)
        p2_grads = p2.get_grad(game, 0)
        
    p1.step(*p1_grads)
    p1.step(*p2_grads)
        

0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990, 

In [6]:
print(p1.w)
print(p1.theta)

[-0.4438557   2.10728522  4.88845041 56.49641025 -0.1571059   1.36152001
  2.83119083  1.59147876  0.43840969]
[1091.07541865  689.28576433  364.59349983  549.06335662  286.92921895
  332.55599919  320.35881683  227.78670044  447.56076629]


In [7]:
game = gomoku.Gomoku(15)
p1.piece = +1
p2.piece = -1

In [8]:
game.play(7, 7)

In [22]:
game.play(*p1.play(game))
game.play(*p2.play(game))
game.show()

AssertionError: game has ended

In [243]:
p1 = player_basic.PGFeaturePlayer('player1', 0)
p2 = player_basic.FeaturePlayer('player2', 0)

In [244]:
for i in range(1000):
    if i%10 == 0:
        print(i, end=', ')
    game = gomoku.Gomoku(9)
    p1color = np.random.choice([1, -1])
    p1.piece = p1color
    p2.piece = -p1color

    players = [p1, p2]
    turn = (1-p1color)//2
    while not game.finished:
        game.play(*players[turn].play(game))
        turn = (turn+1)%2
    
    if game.winner == p1color:
        p1_grads = p1.get_grad(game, 1.)
        #p2_grads = p2.get_grad(game, -1.)
    elif game.winner == -p1color:
        p1_grads = p1.get_grad(game, -1.)
        #p2_grads = p2.get_grad(game, 1.)
    else:
        p1_grads = p1.get_grad(game, 0.)
        #p2_grads = p2.get_grad(game, 0.)
        
    p1.step(*p1_grads)
    #p1.step(*p2_grads)
        

0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990, 

In [245]:
print(p1.w)
print(p1.theta)

[-0.15362757 -0.03364655  0.          0.         -0.0740043  -0.00073599
 -0.03723498 -0.00846379 -0.62696604]
[-0.83542265 -3.15222877 -3.1762802  -3.17800188 -0.48550833 -2.91121014
 -3.05746383 -3.03022919 -6.35600376]


In [255]:
game = gomoku.Gomoku(9)
p1.piece = +1
p2.piece = -1

In [256]:
game.play(*p1.play(game))
game.play(*p2.play(game))
game.show()

[0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
 0.01234568 0.01234568 0.01234568]
   0 1 2 3 4 5 6 7 8
 0 . . . . . . . . . 
 1 . . . . . . . . . 
 2 . . . . . . . . . 
 3 . . 

In [257]:
p1.theta

array([-0.83542265, -3.15222877, -3.1762802 , -3.17800188, -0.48550833,
       -2.91121014, -3.05746383, -3.03022919, -6.35600376])

In [260]:
p1.get_features(game) @ p1.theta

array([[-6.35600376, -6.35600376, -6.35600376, -6.35600376, -6.35600376,
        -6.35600376, -6.35600376, -6.35600376, -6.35600376],
       [-6.35600376, -6.35600376, -6.35600376, -6.35600376, -6.35600376,
        -6.35600376, -6.35600376, -6.35600376, -6.35600376],
       [-6.35600376, -6.35600376, -6.35600376, -6.35600376, -6.35600376,
        -6.35600376, -6.35600376, -6.35600376, -6.35600376],
       [-6.35600376, -6.35600376, -6.35600376, -6.35600376, -6.35600376,
        -6.35600376, -7.1914264 , -7.1914264 , -7.1914264 ],
       [-6.35600376, -6.35600376, -6.35600376, -6.35600376, -6.35600376,
        -6.35600376, -7.67693473, 26.18234874, -7.67693473],
       [-6.35600376, -6.35600376, -6.35600376, -6.35600376, -6.35600376,
        -6.35600376, -7.67693473, 26.18234874, -7.67693473],
       [-6.35600376, -6.35600376, -6.35600376, -6.35600376, -6.35600376,
        -6.35600376, -6.84151208, -6.84151208, -6.84151208],
       [-6.35600376, -6.35600376, -6.35600376, -6.35600376, -6

In [261]:
p1.theta

array([-0.83542265, -3.15222877, -3.1762802 , -3.17800188, -0.48550833,
       -2.91121014, -3.05746383, -3.03022919, -6.35600376])