In [1]:
import numpy as np
import gomoku

# for auto-reloading external modules
%load_ext autoreload
%autoreload 2

In [14]:
game = gomoku.Gomoku(7)
opponent = gomoku.RandomPlayer('player2', -1)

In [15]:
## player turn
x, y = 3, 3
## ===========
game.play(x, y)
game.print()

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [16]:
## opponent turn
x, y = opponent.play(x, y, game)
game.play(x, y)
game.print()

[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0]]
