In [ ]:
## only run if using google Colab 
## For just playing, don't need to run this.
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/gomoku2/')

In [3]:
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

import gomoku
import Paul_player_zero
from time import time
# for auto-reloading external modules
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
## Gobal parameters ==========
SIZE = 9
WIN = 5
N_ITER = 1200
## ===========================
model = Paul_player_zero.net(SIZE)
model.load_weights('day26.h5')

## Human play against AI. Human goes first.

In [6]:
game = gomoku.Gomoku(SIZE)
ai = Paul_player_zero.ZeroPlayer('AI', -1, game, model)
ai.tree.temp = 0.1
ai.tree.epsilon = 0

In [23]:
### Your Move ##########
game.play(3,0)
########################
if not game.finished:
  game.play(*ai.play(game,N_ITER))
game.show()

black played (3, 0).
white played (8, 5).
game has ended. winner: white
   0 1 2 3 4 5 6 7 8
 0 . . . ● . . . ● . 
 1 . . . ○ ○ ○ ● ○ ● 
 2 . ● . . ● ○ ● ○ . 
 3 . ● ○ ● . ● ○ ○ . 
 4 . . ● ○ ● ○ . ○ . 
 5 . ● . ● ○ . . ● ○ 
 6 ○ . ○ ● . ○ . . . 
 7 . . . . . . ● . . 
 8 . . . . . . . . . 


## Human play against AI. Human goes second.

In [ ]:
game = gomoku.Gomoku(SIZE)
ai = Paul_player_zero.ZeroPlayer('AI', 1, game, model)
ai.tree.temp = 0.1
ai.tree.epsilon = 0
game.play(*ai.play(game,N_ITER))
game.show()

In [ ]:
### Your Move ##########
game.play(4,4)
########################
if not game.finished:
  game.play(*ai.play(game,N_ITER))
game.show()

# AI self play

In [26]:
game = gomoku.Gomoku(SIZE)
p1 = Paul_player_zero.ZeroPlayer('p1', +1, game, model)
p2 = Paul_player_zero.ZeroPlayer('p2', -1, game, model)
p1.tree.temp = 0.1
p1.tree.epsilon = 0
p2.tree.temp = 0.1
p2.tree.epsilon = 0
pa, pb = p1, p2 
while not game.finished:
    game.play(*pa.play(game, N_ITER))
    pa, pb = pb, pa
game.show()
############## Also displays the moves in sequence ##################
b= np.zeros((SIZE,SIZE),dtype=np.int8)
b[np.array(game.episode)[:,0],np.array(game.episode)[:,1]] = 1+ np.arange(len(game.episode))
b = b.transpose()
print(b)

white played (2, 0).
black played (8, 0).
game has ended. winner: none
   0 1 2 3 4 5 6 7 8
 0 ● ● ○ ○ ● ○ ○ ● ● 
 1 ○ ● ○ ○ ○ ● ● ○ ● 
 2 ○ ● ○ ● ● ● ● ○ ○ 
 3 ● ○ ● ○ ○ ● ● ● ● 
 4 ○ ● ○ ● ● ○ ○ ○ ○ 
 5 ○ ● ● ● ● ○ ○ ○ ○ 
 6 ○ ● ○ ○ ● ○ ● ● ○ 
 7 ● ○ ● ● ● ○ ○ ● ○ 
 8 ○ ● ● ○ ○ ● ● ○ ● 
[[67 71 80 72 43 74 64 63 81]
 [14 41 40 38 16 39 61 24 73]
 [60 13 18  7 17 25 23 26 66]
 [47 28  5 12  2  9 55 37 57]
 [42 15 20  3 19  4 62 32 44]
 [30 27 29 21  1  8 52 50 54]
 [48 31 22 34 35  6 51 53 56]
 [49 46 79 65 33 10 76 77 58]
 [78 45 75 68 36 11 69 70 59]]
